### ISSUE TITLE
feature request: update packs by share URL or importing pack if possible

### ISSUE THREAD

**Issue by Codingale** [VanillaTweaks/packs#3]
Hey, sorry if this is a terrible place to put this, and I fully understand if this is out of scope of this repo etc but if possible it'd be nice to be able to upgrade the saved packs URLs.

I started at 1.18 and when upgrading to 1.19 saw a link to share it, so I saved it not really testing it and figured I'd be able to upgrade it or something but just discovered it's actually just for 1.19 and if I want one for 1.20 I need to manually select all packs (most if not all have a 1.20 update)

Some ideas you could start a feature like this would be to have a map (JS if server sided code is an issue) and have a mapping of which packs can be updated to which like a linked list for future packs, and in theory reversed for older versions but that may quickly break. If no version for the selected version exists, in that case you can alert them, or maybe suggest a replacement etc

Again, sorry to bother you, happy new year.

**Comment by andre-paulo98** [comment]
The plan for the future will be to instead of directly downloading the pack, it will select the same selection as the share so you can make modifications, this will include changing the version.
As you mentioned this is not the right place for this issue, for the future you can use our feedback form: https://vanillatweaks.net/feedback or chat about this on our discord: https://vanillatweaks.net/discord

There's a bit of a workaround (slightly tedius):
1. Download the pack
2. Open the .zip and extract the `Selected Packs.txt` file
3. Edit that file and change the version to the version you want
4. Upload that file into the website (between the download button and installation process)
