### ISSUE TITLE
if_invisible doesn't target glowing item frames

### ISSUE THREAD

**Issue by SmajloSlovakian** [VanillaTweaks/packs#4]
tested with 2.8.11 armor statues

**Comment by GrantGryczan** [comment]
@SmajloSlovakian The place to report issues is currently here: https://vanillatweaks.net/feedback

But also, this is the fixed in a [newer version](https://www.curseforge.com/minecraft/customization/armor-statues-datapack) that isn't hosted on Vanilla Tweaks. We don't have permission to upgrade it to a newer version, so we've been working on our own overhauled version of the pack to replace it.
